name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Every 6 hours (0, 6, 12, 18)
  schedule:
    - cron: '0 */6 * * *'


jobs:
  compile:
    name: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScipt
        run: npm run build

      - name: Run tests
        run: npm run test
